// Bundle the Hono serverless handler into a single self-contained CommonJS file
// for Vercel. Doing this ourselves (instead of relying on @vercel/node's transform)
// guarantees a CJS output with all workspace + npm deps inlined — no ESM/CJS
// mismatch and no runtime module resolution.
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const entry = path.resolve(here, '../api/index.ts'); // apps/api/api/index.ts
const outfile = path.resolve(here, '../../../api/index.js'); // repo-root/api/index.js

await build({
  entryPoints: [entry],
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node20',
  outfile,
  // Optional/native modules that prod code never actually require()s at runtime.
  external: ['pg-native', 'better-sqlite3'],
  logLevel: 'info',
  banner: { js: '// Generated by build-vercel.mjs — do not edit.' },
});

console.log('✅ Bundled Vercel handler → api/index.js');
